# Refinitiv Data Platform Library for Python
## Function - IPA - IR Swap

This notebook demonstrates how to interest rate Swap using the Instrument Pricing Analytics (IPA) and the Refinitiv Data Libraries.
##### Learn more

To learn more about the Refinitiv Data Library for Python please join the Refinitiv Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the Refinitiv Developer Community portal you will have free access to a number of learning materials like 
 [Quick Start guides](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/quick-start), 
 [Tutorials](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/tutorials), 
 [Documentation](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/documentation)
 and much more.

You may also visit the [API Playground](https://apidocs.refinitiv.com/Apps/ApiDocs) to get more examples, find  end points and download Swagger files

##### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [Refinitiv Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The Refinitiv Developer Community will be happy to help.

## Import the library and connect to Refinitiv Data Libraries

In [1]:
import refinitiv.data as rd
import refinitiv.data.content.ipa.financial_contracts as rdf
from refinitiv.data.content.ipa.financial_contracts import swap

## Open the data session

The open_session() function creates and open sessions based on the information contained in the refinitiv-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [2]:
rd.open_session()

## IR Swap

### Single

In [3]:
response = swap.Definition(
    instrument_tag="EUR_AB6E 5Y swap",
    template="EUR_AB6E",
    tenor="5Y",
).get_data()

response.data.df

,InstrumentDescription,LegDescription,SettlementCcy,InstrumentTag,LegTag,ValuationDate,StartDate,PaymentBusinessDays,EndDate,Tenor,...,PV01AmountInDealCcy,PV01AmountInReportCcy,DV01Bp,DV01AmountInDealCcy,DV01AmountInReportCcy,DiscountCurveName,ForwardCurveName,ErrorCode,ErrorMessage,ProcessingInformation
0,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Pay EUR Annual 3.47%,EUR,EUR_AB6E 5Y swap,PAID,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,44.322508,<NA>,4.525334,452.533428,<NA>,EUR - Swap vs 6M Euribor,<NA>,,,
1,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Receive EUR SemiAnnual +0bp EURIBOR,EUR,EUR_AB6E 5Y swap,RECEIVED,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,-358.532536,<NA>,0.496784,49.678384,<NA>,EUR - Swap vs 6M Euribor,EUR - Swap vs 6M Euribor,,,

### Multiple

In [4]:
response = rdf.Definitions(

    universe=[swap.Definition(
        instrument_tag="EUR_AB6E 5Y swap",
        template="EUR_AB6E",
        tenor="5Y",
    ),
        swap.Definition(
            instrument_tag="EUR_AB6E 5Y swap",
            template="EUR_AB6E",
            tenor="5Y",
    )]
).get_data()

response.data.df

,InstrumentDescription,LegDescription,SettlementCcy,InstrumentTag,LegTag,ValuationDate,StartDate,PaymentBusinessDays,EndDate,Tenor,...,PV01AmountInDealCcy,PV01AmountInReportCcy,DV01Bp,DV01AmountInDealCcy,DV01AmountInReportCcy,DiscountCurveName,ForwardCurveName,ErrorCode,ErrorMessage,ProcessingInformation
0,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Pay EUR Annual 3.47%,EUR,EUR_AB6E 5Y swap,PAID,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,44.322508,<NA>,4.525334,452.533428,<NA>,EUR - Swap vs 6M Euribor,<NA>,,,
1,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Receive EUR SemiAnnual +0bp EURIBOR,EUR,EUR_AB6E 5Y swap,RECEIVED,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,-358.532536,<NA>,0.496784,49.678384,<NA>,EUR - Swap vs 6M Euribor,EUR - Swap vs 6M Euribor,,,
2,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Pay EUR Annual 3.47%,EUR,EUR_AB6E 5Y swap,PAID,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,44.322508,<NA>,4.525334,452.533428,<NA>,EUR - Swap vs 6M Euribor,<NA>,,,
3,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,Receive EUR SemiAnnual +0bp EURIBOR,EUR,EUR_AB6E 5Y swap,RECEIVED,2023-03-07,2023-03-09,EMU,2028-03-09,5Y,...,-358.532536,<NA>,0.496784,49.678384,<NA>,EUR - Swap vs 6M Euribor,EUR - Swap vs 6M Euribor,,,

### Fields selection

In [5]:
response = swap.Definition(
    instrument_tag="EUR_AB6E 5Y swap",
    template="EUR_AB6E",
    tenor="5Y",
    fields=[
        "InstrumentTag",
        "InstrumentDescription",
        "FixedRate",
        "MarketValueInDealCcy",
        "MarketValueInReportCcy",
        "ErrorMessage"
    ],
).get_data()

response.data.df

,InstrumentTag,InstrumentDescription,FixedRate,MarketValueInDealCcy,MarketValueInReportCcy,ErrorMessage
0,EUR_AB6E 5Y swap,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,0.034717,156204.339317,<NA>,
1,EUR_AB6E 5Y swap,Pay EUR Annual 3.47% vs Receive EUR SemiAnnual...,<NA>,156204.339317,<NA>,

### Global calculation parameters

In [6]:
response = rdf.Definitions(

    universe=[swap.Definition(
        instrument_tag="EUR_AB6E 5Y swap",
        template="EUR_AB6E",
        tenor="5Y")
    ],
    pricing_parameters=swap.PricingParameters(
        valuation_date="2018-01-10T00:00:00Z",
        report_ccy='JPY')

).get_data()

response.data.df

,InstrumentDescription,LegDescription,SettlementCcy,InstrumentTag,LegTag,ValuationDate,StartDate,PaymentBusinessDays,EndDate,Tenor,...,PV01AmountInDealCcy,PV01AmountInReportCcy,DV01Bp,DV01AmountInDealCcy,DV01AmountInReportCcy,DiscountCurveName,ForwardCurveName,ErrorCode,ErrorMessage,ProcessingInformation
0,Pay EUR Annual 0.32% vs Receive EUR SemiAnnual...,Pay EUR Annual 0.32%,EUR,EUR_AB6E 5Y swap,PAID,2018-01-10,2018-01-12,EMU,2023-01-12,5Y,...,4.749831,632.351603,4.957216,495.721647,65996.115669,EUR - Swap vs 6M Euribor,<NA>,,,
1,Pay EUR Annual 0.32% vs Receive EUR SemiAnnual...,Receive EUR SemiAnnual +0bp EURIBOR,EUR,EUR_AB6E 5Y swap,RECEIVED,2018-01-10,2018-01-12,EMU,2023-01-12,5Y,...,-440.745847,-58677.110544,0.50226,50.22597,6686.653522,EUR - Swap vs 6M Euribor,EUR - Swap vs 6M Euribor,,,

### Global & individual calculation parameters

In [7]:
response = rdf.Definitions(

    universe=[swap.Definition(
        instrument_tag="EUR_AB6E 5Y swap",
        template="EUR_AB6E",
        tenor="5Y",
        pricing_parameters=swap.PricingParameters(
            valuation_date="2018-01-10T00:00:00Z",
            report_ccy='JPY')
    )],

    pricing_parameters=swap.PricingParameters(
        valuation_date="2018-01-10T00:00:00Z",
        report_ccy='JPY')
).get_data()

response.data.df

,InstrumentDescription,LegDescription,SettlementCcy,InstrumentTag,LegTag,ValuationDate,StartDate,PaymentBusinessDays,EndDate,Tenor,...,PV01AmountInDealCcy,PV01AmountInReportCcy,DV01Bp,DV01AmountInDealCcy,DV01AmountInReportCcy,DiscountCurveName,ForwardCurveName,ErrorCode,ErrorMessage,ProcessingInformation
0,Pay EUR Annual 0.32% vs Receive EUR SemiAnnual...,Pay EUR Annual 0.32%,EUR,EUR_AB6E 5Y swap,PAID,2018-01-10,2018-01-12,EMU,2023-01-12,5Y,...,4.749831,632.351603,4.957216,495.721647,65996.115669,EUR - Swap vs 6M Euribor,<NA>,,,
1,Pay EUR Annual 0.32% vs Receive EUR SemiAnnual...,Receive EUR SemiAnnual +0bp EURIBOR,EUR,EUR_AB6E 5Y swap,RECEIVED,2018-01-10,2018-01-12,EMU,2023-01-12,5Y,...,-440.745847,-58677.110544,0.50226,50.22597,6686.653522,EUR - Swap vs 6M Euribor,EUR - Swap vs 6M Euribor,,,

## Close the default session

In [8]:
rd.close_session()